version: '3.8'
x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},d{3}) (?P<message>(?s:.*))$$'

services:
  postgres:
    image: postgres:15.5
    env_file:
      - stack.env
    volumes:
      - ${PROJ_DATA_DIR}/Relo_DB:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${AIRFLOW_DB}" ]
      interval: 5s
      retries: 5
    restart: always

  airflow:
    image: apache/airflow:2.9.0-python3.11
    volumes:
      - ${PROJ_DIR}/airflow/:/opt/airflow/
    ports:
      - "8080:8080"
    env_file:
      - stack.env
    command: airflow standalone

  jupyter:
    image: denk2/relo_jupyter:0.1.0
    env_file:
      - stack.env
    volumes:
      - ${PROJ_DIR}/scraping:/home/jovyan/scripts/
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    restart: always

  relohelper:
    image: denk2/relohelper:v0.3.0
    command: python main.py
    env_file:
      - stack.env
    ports:
      - "80:8000"
    depends_on:
      - loki
      - postgres
      - prometheus
    logging: *default-logging

  loki:
    image: grafana/loki:2.9.3
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.48.1
    ports:
      - "9090:9090"
    volumes:
      - ${PROJ_DIR}/fastapi/etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki
    logging: *default-logging

  tempo:
    image: grafana/tempo:2.3.1
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - loki
    logging: *default-logging

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    volumes:
      - ${PROJ_DIR}/fastapi/etc/grafana/:/etc/grafana/provisioning/datasources
      - ${PROJ_DIR}/fastapi/etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ${PROJ_DIR}/fastapi/etc/dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    logging: *default-logging