# === Black ===
[tool.black]
line-length = 88
include = '\.pyi?$'
extend-exclude = '''
/(
  | dist
  | .pytest_cache
  | .tox
  | docs
  | docs_src
  | .venv
  | .mypy_cache
)/
'''

# === Ruff ===
[tool.ruff]
line-length = 88
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP", # pyupgrade
    "D",  # pydocstyle
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM",  # flake8-simplify
    "PTH",  # flake8-use-pathlib
    "DTZ",  # flake8-datetimez
    #    "S",  # flake8-bandit
    "N",  # PEP8-naming
    "I",  # isort
    "PT"  # flake8-pytest-style
]
ignore = [
    "F403",
    "B008",
    "B026",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "N805",
]

[tool.ruff.pydocstyle]
convention = "google"